# Generated by Django 4.1 on 2023-02-22 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_create_date_post_created_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="created_date",
            new_name="create_date",
        ),
    ]
