# Generated by Django 4.1 on 2023-02-22 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_created_date_comment_create_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="create_date",
            new_name="created_date",
        ),
    ]
